# Aeterna disk image configuration

IMAGE_SIZE="4G"
IMAGE_FILE="build/aeterna-0.1.0-dev-amd64.img"

EFI_SIZE="512M"

EFI_LABEL="AETERNA_EFI"
ROOT_LABEL="AETERNA_ROOT"

EFI_MOUNT="/mnt/aeterna-root/boot/efi"
ROOT_MOUNT="/mnt/aeterna-root"
