# Aeterna source configuration

KERNEL_NAME="linux"
KERNEL_VERSION="7.2.8"

KERNEL_ARCHIVE="${KERNEL_NAME}-${KERNEL_VERSION}.tar.xz"
KERNEL_SIGNATURE="${KERNEL_NAME}-${KERNEL_VERSION}.tar.sign"

KERNEL_BASE_URL="https://www.kernel.org/pub/linux/kernel/v7.x"

KERNEL_ARCHIVE_URL="${KERNEL_BASE_URL}/${KERNEL_ARCHIVE}"
KERNEL_SIGNATURE_URL="${KERNEL_BASE_URL}/${KERNEL_SIGNATURE}"
